# Generated by Django 3.1.3 on 2021-09-15 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlinecourse', '0004_auto_20210915_1036'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='question_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
