# Generated by Django 3.1.3 on 2021-09-16 05:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onlinecourse', '0009_auto_20210915_1933'),
    ]

    operations = [
        migrations.RenameField(
            model_name='submission',
            old_name='chocies',
            new_name='choices',
        ),
    ]
